root = "."
tmp_dir = "tmp"

[build]
# Build cho server chính
cmd = "go build -o tmp/server ./cmd/server"
bin = "tmp/server"
full_bin = "tmp/server"
include_ext = ["go", "html", "css", "js"]
exclude_dir = ["tmp", "vendor"]
delay = 1000

[log]
time = true