root    = "."
tmp_dir = "tmp"

[build]

# Build command
cmd = "go build -o ./tmp/server ./cmd/api"

# Binary path
bin = "./tmp/server"

# Execute binary
full_bin = "./tmp/server"

# Watch extensions
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env"]

# Ignore folders
exclude_dir = [
  "tmp",
  "vendor",
  "node_modules",
  ".git",
  "storage",
  "logs"
]

# Ignore files
exclude_file = []

# Delay before rebuild (ms)
delay = 1000

# Docker/Linux compatibility
poll = true

# Graceful restart
send_interrupt = true
kill_delay = "500ms"

# Stop build on error
stop_on_error = true

# Follow symlink
follow_symlink = true

# Log build errors
log = "air_errors.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true