version: "3.9"

services:
  # 1. Main API Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "${HOST_APP}:${PORT_APP}"
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DBUser}
      DB_PASSWORD: ${DBPassword}
      DB_NAME: ${DBName}
      RABBITMQ_URL: amqp://${RabbitMQUser}:${RabbitMQPassword}@rabbitmq:5672/
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ALLOWED_API_KEYS: ${ALLOWED_API_KEYS}

  # 3. Database (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: primary_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DBUser}
      POSTGRES_PASSWORD: ${DBPassword}
      POSTGRES_DB: ${DBName}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 4. Message Queue (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQUser}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQPassword}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # 5. Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: app_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./web/static:/app/web/static:ro
    depends_on:
      - app
      # - kong

  # 6. Kong API Gateway
  # kong:
  #   image: kong:latest
  #   container_name: app_kong
  #   environment:
  #     KONG_DATABASE: "off"
  #     KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
  #     KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  #     KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  #     KONG_TRUSTED_IPS: "0.0.0.0/0, ::/0"
  #     KONG_REAL_IP_HEADER: "X-Forwarded-For"
  #     JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  #   volumes:
  #     - ./kong/kong.yml:/kong/kong.yml:ro
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"
  #   depends_on:
  #     - app

volumes:
  pgdata:
  rabbitmq_data:
