version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${HOST_APP}:${PORT_APP}"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ALLOWED_API_KEYS: ${ALLOWED_API_KEYS}
      DB_REPLICA_HOSTS: ${DB_REPLICA_HOSTS}

  db:
    image: postgres:16
    container_name: primary_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # replica:
  #   image: postgres:16
  #   container_name: replica_db
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     POSTGRES_USER: ${DB_USER_REP}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD_REP}
  #     POSTGRES_DB: ${DB_NAME_REP}
  #   depends_on:
  #     - db
  #   volumes:
  #     - replica_data:/var/lib/postgresql/data

volumes:
  pgdata:
  rabbitmq_data:
  #replica_data: